[tox]
envlist = py{310,311,312,313,314}

[base]
deps = pytest
       packaging
       cython>=3.0
       pure-sasl
       kerberos
       lz4
       cryptography>=42.0

[testenv]
deps = {[base]deps}

setenv = LIBEV_EMBED=0
         CARES_EMBED=0
         LC_ALL=en_US.UTF-8
changedir = {envtmpdir}
commands = pytest -v {toxinidir}/tests/unit/

