name: Test building on pre-release python version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to run against'
        required: true
        type: string

      target:
        type: string
        description: "target os to build for: linux,macos,windows"
        default: "linux,macos,windows"

      cibw-skip:
        type: string
        description: 'CIBUILDWHEEL builds pattern to skip, goes to CIBW_SKIP env'
        required: false
        default: 'cp36* cp37* pp*i686 *musllinux*'

jobs:
  build-and-publish:
    uses: ./.github/workflows/lib-build-and-push.yml
    with:
      python-version: ${{ inputs.python-version }}
      target: ${{ inputs.target }}
      cibw-skip: ${{ inputs.cibw-skip }}
