name: Test building on pre-release python version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to run against'
        required: true
        type: string

      target:
        type: string
        description: "target os to build for: linux,macos-x86,macos-arm,windows,linux-aarch64"
        default: "linux,macos-x86,macos-arm,windows,linux-aarch64"

jobs:
  build-and-publish:
    uses: ./.github/workflows/lib-build-and-push.yml
    with:
      python-version: ${{ inputs.python-version }}
      target: ${{ inputs.target }}
