name: "Docs / Publish"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    branches:
      - master
      - 'branch-**'
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up env
        run: make -C docs setupenv
      - name: Build docs
        run: make -C docs multiversion
      - name: Build redirects
        run: make -C docs redirects
      - name: Deploy docs to GitHub Pages
        run: ./docs/_utils/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
